test: FSC git action
optimizely/swift-sdk pull request #458
Opened 2022-06-28 15:41 UTC by ozayr-zaviar

## Summary
- The "what"; a concise description of each logical change
- Another change

The "why", or other context.

## Test plan

## Issues
- "THING-1234" or "Fixes #123"

2022-07-11 23:45 UTC, msohailhussain commented on .github/workflows/integration_tests.yml
> +        ref: 'mnoman/gitActions'
```suggestion
        ref: 'master'
```

2022-07-12 00:17 UTC, jaeopt requested changes
a fix suggested

2022-07-12 00:17 UTC, jaeopt commented on .github/workflows/swift.yml
> +    uses: optimizely/swift-sdk/.github/workflows/integration_tests.yml@uzair/test-with-fsc
same here?  should be @master ?

2022-07-12 00:38 UTC, msohailhussain approved these changes
lgtm

2022-07-12 00:52 UTC, jaeopt approved these changes

2022-07-12 00:52 UTC, merged