refact(odp): Allows support for ODP testing using FSC.
optimizely/swift-sdk pull request #476
Opened 2023-02-02 11:18 UTC by yasirfolio3

## Summary
- Provides access to some ODP classes for testing purpose.

## Test plan
- All tests should pass

## Issues
- FSSDK-8042

2023-02-02 18:09 UTC, jaeopt requested changes
It looks great. One change suggested - I do not see the reason we want to open OdpConfig.

2023-02-02 18:59 UTC, yasirfolio3 commented on Sources/ODP/OdpConfig.swift
> +public class OdpConfig {
This is necessary since `OdpEventManager`'s contructor requires this class.

2023-02-02 21:29 UTC, jaeopt commented on Sources/ODP/OdpConfig.swift
> +public class OdpConfig {
Got it! I removed OdpConfig from OdpEventManager and OdpSegmentManager init methods to support customization without opening OdpConfig. Please review this PR first (https://github.com/optimizely/swift-sdk/pull/476) and then we can remove `public` here.

2023-02-08 08:49 UTC, yasirfolio3 commented
@jaeopt Verified it with latest FSC tests: https://github.com/optimizely/fullstack-sdk-compatibility-suite/actions/runs/4122123976/jobs/7118530491

2023-02-08 16:46 UTC, jaeopt approved these changes
LGTM

2023-02-08 19:07 UTC, merged