[FSSDK-9776] handle duplicate experiment key
optimizely/swift-sdk pull request #523
Opened 2023-11-24 16:49 UTC by muzahidul-opti

## Summary
When duplicate experiment key found in the data file, SDK returns correct experiment map in  OptimizelyConfig

- Keep latest experiment key, found in the datafile experiment list
- Add warning log "Duplicate keys found in datafile: {key-name}"

## Test plan
- Add test case for OptimizelyConfig with duplicate key

## Issues
- [FSSDK-9776](https://jira.sso.episerver.net/browse/FSSDK-9776)

2023-11-27 16:03 UTC, mikechu-optimizely submitted a review, later dismissed
Some thoughts but LGTM.

2023-11-28 08:22 UTC, muzahidul-opti commented on Tests/OptimizelyTests-APIs/OptimizelyClientTests_OptimizelyConfig.swift
> +		XCTAssertEqual(optimizelyExpMap["duplicate_key"]?.id, "10005")
Logger test added

2023-11-28 17:21 UTC, jaeopt requested changes
Looks good. Can you check why your code format/styles are different from existing codes?

2023-11-29 13:59 UTC, mikechu-optimizely commented
Can I use this as a reference for doing other language SDK updates?

2023-11-29 14:36 UTC, muzahidul-opti commented
> Can I use this as a reference for doing other language SDK updates?

Sure

2023-11-29 15:27 UTC, mikechu-optimizely commented
Thanks for the lint fixes. This helps my need for meticulous code.  😄 

Also thanks for the reference implementation for me to copy 😁

2023-11-30 10:48 UTC, merged